spring:
  profiles.active: @activatedProperties@
  application:
    name: music-library
  data:
    rest:
      basePath: /api
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialize: true
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
server.port: 8080
logging:
  level:
    ROOT: INFO
    org.springframework.cloud.config: OFF